# Generated by Django 4.2.3 on 2023-07-15 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_alter_lesson_title_coursesubscription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursesubscription',
            options={'verbose_name': 'подписка', 'verbose_name_plural': 'подписки'},
        ),
        migrations.RemoveField(
            model_name='coursesubscription',
            name='update_version',
        ),
    ]