# Generated by Django 4.2.3 on 2023-07-15 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_payment_paid_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('Create', 'создано'), ('Paid', 'оплачено')], default='Create', max_length=50, verbose_name='статус оплаты'),
        ),
    ]