# Generated by Django 4.2.3 on 2023-07-17 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0006_alter_coursesubscription_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesubscription',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='признак подписки'),
        ),
        migrations.AlterField(
            model_name='coursesubscription',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
    ]